### ISSUE TITLE
Mongodb ObjectId

### ISSUE THREAD

**Issue by GitProdEnv** [oun/kafka-event-router#1]
My id is of type ObjectId with key's payload of { "id" : "{\"$oid\" : \"596e275826f08b2730779e1f\"}" }.

I saw that you used a uuid instead of a Mongodb ObjectId.

How can I get the $oid value as my EVENT_ID?
Thank you so much.

**Comment by oun** [comment]
I will update code to support your use case.
Thanks.

**Comment by GitProdEnv** [comment]
Thank you so much, and for this quick response.
